version: 1.0.{build}-alpha1
branches:
  only:
  - master
image: Visual Studio 2017
clone_folder: c:\projects\NWheels
before_build:
- cmd: >-
    cd c:\projects\NWheels\Source
    dotnet --version
    dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    cd c:\projects\NWheels\Source
    dotnet publish
test_script:
- cmd: >-
    cd c:\projects\NWheels\Source
    dotnet test NWheels.Implementation.UnitTests\NWheels.Implementation.UnitTests.csproj
    dotnet test NWheels.Injection.Adapters.Autofac.UnitTests\NWheels.Injection.Adapters.Autofac.UnitTests.csproj
    dotnet test NWheels.Compilation.Adapters.Roslyn.UnitTests\NWheels.Compilation.Adapters.Roslyn.UnitTests.csproj
    dotnet test NWheels.Platform.Rest.Implementation.UnitTests\NWheels.Platform.Rest.Implementation.UnitTests.csproj
    dotnet test NWheels.Platform.Messaging.UnitTests\NWheels.Platform.Messaging.UnitTests.csproj
    dotnet test NWheels.Frameworks.Ddd.Implementation.UnitTests\NWheels.Frameworks.Ddd.Implementation.UnitTests.csproj
